# Generated by Django 2.0.6 on 2018-06-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('textoprevio', models.CharField(max_length=200)),
                ('imagenportada', models.ImageField(upload_to='media/')),
                ('textograndecuerpo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('publicidad1', models.ImageField(upload_to='media/')),
                ('publicidad2', models.ImageField(upload_to='media/')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecategoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreregion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='articulos.Categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona', to='articulos.Region'),
        ),
    ]
