# Generated by Django 2.0.6 on 2018-07-02 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('textoprevio', models.CharField(max_length=200)),
                ('imagenportada', models.ImageField(upload_to='media/')),
                ('textograndecuerpo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('patrocinado', 'patrocinado'), ('prueba', 'prueba'), ('corporativo', 'corporativo'), ('institucional', 'institucional'), ('estrategico', 'estrategico')], default='patrocinado', max_length=50)),
                ('cuerpo', models.TextField()),
                ('publicidad1', models.ImageField(upload_to='media/')),
                ('link1', models.URLField(blank=True, null=True)),
                ('publicidad2', models.ImageField(upload_to='media/')),
                ('link2', models.URLField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('fechainicio', models.DateField(auto_now_add=True)),
                ('fechafin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecategoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patrocinador', models.CharField(max_length=100)),
                ('razonsocial', models.CharField(max_length=200)),
                ('fechacontrato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreregion', models.CharField(max_length=200)),
                ('Usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ManyToManyField(to='articulos.Region'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='articulos.Categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona', to='articulos.Region'),
        ),
    ]
