# Generated by Django 2.0.6 on 2018-06-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('textoprevio', models.CharField(max_length=200)),
                ('imagenportada', models.ImageField(upload_to='media/')),
                ('textograndecuerpo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('publicidad1', models.ImageField(upload_to='media/')),
                ('publicidad2', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
