# Generated by Django 2.0.6 on 2018-08-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_aleatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='revistas/'),
        ),
    ]
