# Generated by Django 2.0.6 on 2018-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_region_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='linkvideo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='videoin',
            field=models.BooleanField(default=False),
        ),
    ]
